### ISSUE TITLE
NameError: name 'date' is not defined

### ISSUE THREAD

**Issue by histefanhere** [bradleypallen/doomsday#2]
Hey Bradley,

Awesome package, but I'm getting an error with certain dates:

```
$ doomsday dayofweek --explain 2021-01-15
Traceback (most recent call last):
  File "/home/stoofin/.local/bin/doomsday", line 8, in <module>
    sys.exit(cli())
  File "/home/stoofin/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/stoofin/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/stoofin/.local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stoofin/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stoofin/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/stoofin/.local/lib/python3.6/site-packages/doomsday/cli.py", line 178, in dayofweek
    explain_doomsmonth(date.year, date.month, date.day)
  File "/home/stoofin/.local/lib/python3.6/site-packages/doomsday/cli.py", line 77, in explain_doomsmonth
    print("%d %s%s a leap year, so" % (date.year, correct_tense(date, "was", "is", "will be"), "" if methods.leapyear(year) else " not")),
NameError: name 'date' is not defined
```

It seems to affect dates that are in January or February. Upon inspection of the code, it does seem like `date` comes out outa nowhere

**Comment by bradleypallen** [comment]
Thanks very much for submitting this, apologies for the lengthy response time. Fixed.
